docker-backend-repo: thesis-backend
docker-frontend-repo: thesis-frontend
infrastructure-repo: thesis-infrastructure
backup-input-repo: thesis-backup-files
tier: frontend
default-input-prod: false
default-input-release: false
default-input-feature: false
